---
title: "R Notebook"
output: html_notebook
---

# Exercícios Manipulação e Importação de Dados


# Exercicio 1 - Encontre e faça a correção do erro na instrução abaixo:
write.table(mtcars, file = "mtcars2.txt", sep = "|", col.names = N, qmethod = "double")

## Correto: 
write.table(mtcars, file = "mtcars2.txt", sep = "|", col.names = NA, qmethod = "double")

---------------------------------------------------------------------------------------------------------


# Exercicio 2 - Encontre e faça a correção do erro na instrução abaixo:
# Troubleshooting - tentar descobrir a causa do problema
# Processo de análise do problema

---------------------------------------------------------------------------------------------------------
                                          # vignette("readr")
                                    # INTRODUÇÂO COMPLETA AO READR
---------------------------------------------------------------------------------------------------------
library(readr)
?read_csv
df_iris <- read_csv("iris.csv", col_types = matrix( # grava no formato tibble
  Sepal.Length = col_double(1),
  Sepal.Width = col_double(1),
  Petal.Length = col_double(1),
  Petal.Width = col_double(1),
  Species = col_factor(c("setosa", "versicolor", "virginica"))
))

## Correto: 
library(readr)
df_iris <- read_csv("iris.csv", col_types = list(   # uso do objeto lista
    Sepal.Length = col_double(),
    Sepal.Width = col_double(),
    Petal.Length = col_double(),
    Petal.Width = col_double(),
    Species = col_factor(c("setosa", "versicolor", "virginica"))
))

---------------------------------------------------------------------------------------------------------

# Exercício 3 - Abaixo você encontra dois histogramas criados separadamente.
# Mas isso dificulta a comparação das distribuições. 
#Crie um novo plot que faça a união de ambos histogramas em apenas uma área de plotagem.

# Dados aleatórios
dataset1=rnorm(4000 , 100 , 30)     
dataset2=rnorm(4000 , 200 , 30) 

# Histogramas par distribuição de frequências dos dados
par(mfrow=c(1,2))

hist(dataset1, breaks=30 , xlim=c(0,300) , col=rgb(1,0,0,0.5) , xlab="Altura" , ylab="Peso" , main="" )

hist(dataset2, breaks=30 , xlim=c(0,300) , col=rgb(0,0,1,0.5) , xlab="Altura" , ylab="Peso" , main="")


# Histogramas tranpostos - intersecção
hist(dataset1, breaks=30, xlim=c(0,300), col=rgb(1,0,0,0.5), xlab="height", ylab="nbr of plants", main="distribution of height of 2 durum wheat varieties" )

hist(dataset2, breaks=30, xlim=c(0,300), col=rgb(0,0,1,0.5), add=T) # parametro transposto
legend("topright", legend=c("Dataset 1","Dataset 2"), col=c(rgb(1,0,0,0.5), 
                                                      rgb(0,0,1,0.5)), pt.cex=2, pch=15 )


---------------------------------------------------------------------------------------------------------

# Exercício 4 - Encontre e corrija o erro no gráfico abaixo
install.packages("plotly")
library(plotly)
View(iris)


#object species not found
plot_ly(iris, 
        x = ~Petal.Length, 
        y = ~Petal.Width,  
        type ="scatter", 
        mode = "markers" , 
        color = Species , marker=list(size=20 , opacity=0.5))


## A função plot_ly especifica ao final a necessidade do caracter ~
?plot_ly # consultar a documentação 
plot_ly(iris, 
        x = ~Petal.Length, 
        y = ~Petal.Width,  
        type ="scatter", 
        mode = "markers" , 
        color = ~Species , marker=list( size=20 , opacity=0.5))


--------------------------------------------------------------------------------------------------------- 
                                           # r-graph-gallery
---------------------------------------------------------------------------------------------------------

# Exercício 5 - Em anexo você encontra o arquivo exercicio5.png. Crie o gráfico que resulta nesta imagem.
# https://www.r-graph-gallery.com/111-interactive-3d-plot-plotly/


library(plotly) # gráfico de vulcão disponível no plotly
head(volcano)
?volcano

# 3D plot :
p = plot_ly(z = volcano, type = "surface")
p

---------------------------------------------------------------------------------------------------------

# Exercício 6 - Carregue o arquivo input.json anexo a este script e imprima o conteúdo no console
# Dica: Use o pacote rjson - javascrpit object notation

library("rjson") # basta carregar
result <- fromJSON(file = "input.json")
print(result)
class(result) # objeto lista criado

---------------------------------------------------------------------------------------------------------

# Exercício 7 - Converta o objeto criado ao carregar o arquivo json do exercício anterior 
# em um dataframe e imprima o conteúdo no console.

library("rjson")
result <- fromJSON(file = "input.json")
class(result)
json_data_frame <- as.data.frame(result) # gravar em outro objeto como data.frame
print(json_data_frame)
class(json_data_frame) # objeto data.frame
View(json_data_frame)

---------------------------------------------------------------------------------------------------------

# Exercício 8 - Carregue o arquivo input.xml anexo a este script.
# Dica: Use o pacote XML
install.packages("XML")
library("XML")
library("methods")

result <- xmlParse(file = "input.xml")
print(result)
class(result)

---------------------------------------------------------------------------------------------------------

# Exercício 9 - Converta o objeto criado no exercício anterior em um dataframe

xmldataframe <- xmlToDataFrame("input.xml")
print(xmldataframe)
class(xmldataframe)
View(xmldataframe)

---------------------------------------------------------------------------------------------------------

# Exercício 10 - Carregue o arquivo input.csv em anexo e então responda às seguintes perguntas:

# Pergunta 1 - Quantas linhas e quantas colunas tem o objeto resultante em R?
# Pergunta 2 - Qual o maior salário?
# Pergunta 3 - Imprima no console o registro da pessoa com o maior salário.
# Pergunta 4 - Imprima no console todas as pessoas que trabalham no departamento de IT.
# Pergunta 5 - Imprima no console as pessoas do departamento de IT com salário superior a 600. 


data <- read.csv("input.csv") #utils
print(data)
View(data) # visualizamos no formato de tabela

# 1
print(is.data.frame(data)) #primeiramente, é um dataframe?
print(ncol(data)) #função número de colunas
print(nrow(data)) #função número de linhas
dim(data)

# 2
# Get the max salary from data frame.
sal <- max(data$salary) #chamar apenas a coluna salary e passar na função max
print(sal)

# 3
# Get the person detail having max salary. Neste caso imprimir o registro completo
# Subset para extrari o registro
retval <- subset(data, salary == max(salary))
# função subset, pesquisar no dataset o salário que seja igual ao salário maior
print(retval)

# 4
retval <- subset(data, dept == "IT")
# função subset, pesquisar no dataset todas as pessoas que tem departamento igual a "IT"
print(retval)

# 5
# função subset, pesquisar no dataset todos no departamento de "IT" com salario > 600
info <- subset(data, salary > 600 & dept == "IT")
print(info)



