---
title: "R Notebook"
output: html_notebook
---
                        
                                                
              # Pacote Lattice focado em pesquisadores e análise multivariada

# Se necessário comparar diversas variáveis simultaneamente, pode ser mais útil que ggplot


# O pacote Lattice é um sistema de visualização de dados em alto nível
# de alto nível poderoso e elegante, com ênfase em dados 

# O conceito por trás do Latticeé em agrupar os dados e criar visualizaçãoes de forma 
# que fique mais fácil a BUSCA POR PADRÕES

# Instala e carrega o pacote
install.packages('lattice')
library(lattice)

========================================================================================

# ScatterPlot com Lattice - xyplot()
View(iris)

xyplot(data = iris, 
       groups = Species,            # utilizar como grupo a variável species
       Sepal.Length ~ Petal.Length) # relação entre as duas variáveis que indicam características


========================================================================================

# BarPlots com dataset Titanic - barchart()
# Várias informações em apenas uma área de plotagem e DETECTAR PADRÕES

?Titanic

barchart(Class ~ Freq | Sex + Age, # relação de classe e frequência, sexo e idade, unir todas as variáveis em uma única área
         data = as.data.frame(Titanic), #conjunto de dados titanic como data.frame
         groups = Survived,  #groups para fazer agrupamento de sobreviventes
         stack = T, #habilitar gráficos juntos ou não
         layout = c(4, 1), #layout de como agrupar as caixas
         auto.key = list(title = "Dados Titanic", #usar uma lista 
                         columns = 2)) 

barchart(Class ~ Freq | Sex + Age, 
         data = as.data.frame(Titanic),
         groups = Survived, 
         stack = T,
         layout = c(4, 1),
         auto.key = list(title = "Dados Titanic", 
         columns = 2),
         scales = list(x = "free")) #escala

========================================================================================


# Contagem de elementos
PetalLength <- equal.count(iris$Petal.Length, 4)
PetalLength

# ScatterPlots xyplot()
xyplot(Sepal.Length~Sepal.Width | PetalLength, data = iris)
       #relação entre essas duas  #com esta    #dataset


# Aplicação de grid() para dimensionar e melhor visualizar a informação
xyplot(Sepal.Length~Sepal.Width | PetalLength, data = iris,
       panel = function(...) {
         panel.grid(h = -1, v = -1, col.line = "skyblue") 
         panel.xyplot(...)})


xyplot(Sepal.Length~Sepal.Width | PetalLength, data = iris,
       #relação entre essas duas  #com esta    #dataset
       panel = function(x,y,...) {
         panel.xyplot(x,y,...)
         mylm <- lm(y~x) #ao invés do grid aplicando a linha de regressão em cada caix
         panel.abline(mylm)})


histogram(~Sepal.Length | Species, xlab = "",
          data = iris, layout=c(3,1), type = "density",
          main = "Histograma Lattice", sub = "Iris Dataset, Sepal Length")


# Distribuição dos dados
qqmath(~ Sepal.Length | Species, data = iris, distribution = qunif)


# Boxplot
bwplot(Species~Sepal.Length, data = iris)


# ViolinPlot ajuda a compreender como os dados estão distribuídos assim como histograma
bwplot(Species~Sepal.Length, data = iris,
       panel = panel.violin)



