---
title: "R Notebook"
output: html_notebook
---

                                # Mapas

# Uma empresa de segurança gostaria de ter um modelo preditivo a fim de:
# prever a ocorrência de crimes em uma determinada cidade

# ocorrências de crimes passados para desenvolver a modelagem 
# treina o modelo de machine learning e faz uma sequência de previsões

# Instala os pacotes
install.packages(c("ggplot2", "maps", "mapdata"))

# Carrega os pacotes
library(ggplot2) # mapas criados com ggplot2 
library(maps)    # pacote maps para obter dados de mapas
library(mapdata) # mapdata para tratar destes dados

====================================================================================

# Função para buscar as coordenadas dos países
# Este pacote dispõe de todas as coordenadas do mundo

?map_data # pertence ao ggplot2 

mapa <- map_data("world") # obter dados do mundo e passar para o objeto mapa

# Visualizando o dataframe
dim(mapa)  # datatrame de 6 colunas e 99mil observações
View(mapa) # visualizar em tabela

====================================================================================

# Gerando o Mapa com ggplot com geom_polygon

          #Nova geometria
ggplot() + geom_polygon(data = mapa,         # data mundo
                        aes(x=long, y = lat, # aesthetics
                        group = group)) +    # grupos
                        coord_fixed(1.3)     # coordenadas

#output com mapa completo, branco e preto e grids

====================================================================================

ggplot() + 
  geom_polygon(data = mapa, 
               aes(x=long, y = lat, group = group), 
               fill = NA, # tirar preenchimento preto
               color = "blue") +  # acrescentar contorno em azul nas delimitações regionais
               coord_fixed(1.3)

====================================================================================

gg1 <- ggplot() + 
  geom_polygon(data = mapa, # data mundo
               aes(x=long, y = lat, group = group), 
               fill = "seagreen1", # preenchimento com cor diferente
               color = "blue") + 
  coord_fixed(1.3)
gg1

==================================================================================== 

#Marcando alguns pontos no mapa

# Podemos usar um shapefile se o conjunto de dados não possuir coordenadas
# Quem fornece este tipo de arquivo é o IBGE, download diretamente e carregá-los

labs <- data.frame(
  long = c(69.24140, -2.8456051),
  lat = c(-78.38995, 22.44512),
  names = c("Ponto1", "Ponto2"), # criando vetor de dois pontos de dados
  stringsAsFactors = FALSE
)  

====================================================================================

# Pontos no mapa

gg1 + # já foi criado anteriormente

# Adicionando duas geometrias com geom_point duas vezes
  geom_point(data = labs, aes(x = long, y = lat), color = "black", size = 2) +
  geom_point(data = labs, aes(x = long, y = lat), color = "yellow", size = 2)


====================================================================================

# Divisão por países

ggplot(data = mapa) +                 #preenchimento país
  geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "white") + 
  coord_fixed(1.3) +
  guides(fill=FALSE) # guides igual a false e fazer preenchimento em todos os países


# rMaps  - Forma interativa de criar mapas em R 
# require(devtools)
# install_github
# http://rmaps.github.io
  
  
  