---
title: "R Notebook"
output: html_notebook
---



# Expressões Regulares - Recurso muito útil em mineração de texto

# Determina um padrão e depois busca por esse padrão dentro de um texto, uma string, uma frase.


========================================================================================================================

                                       # Lista de funções


# grep(pattern, x, ignore.case = FALSE, perl = FALSE, value = FALSE, fixed = FALSE, useBytes = FALSE, invert = FALSE)

# grepl(pattern, x, ignore.case = FALSE, perl = FALSE, fixed = FALSE, useBytes = FALSE)

# sub(pattern, replacement, x, ignore.case = FALSE, perl = FALSE, fixed = FALSE, useBytes = FALSE)

# gsub(pattern, replacement, x, ignore.case = FALSE, perl = FALSE, fixed = FALSE, useBytes = FALSE)

# regexpr(pattern, text, ignore.case = FALSE, perl = FALSE, fixed = FALSE, useBytes = FALSE)

# gregexpr(pattern, text, ignore.case = FALSE, perl = FALSE, fixed = FALSE, useBytes = FALSE)

str <- c("Expressões", "regulares", "em linguagem R", 
         "permitem a busca de padrões", "e exploração de textos",
         "podemos buscar padrões em dígitos",
         "como por exemplo",
         "10992451280")

length(str) # oito posições no vetor str  o. 8
str

========================================================================================================================
                            

                        # grep() - Pattern Matching and Replacement

?grep
grep("ex", str, value = F)  # indica posição dentro do vetor
grep("ex", str, value = T)  # mostra qual frase possui o padrão dentro do vetor
grep("\\d", str, value = F) # \\ buscar por tudo que for digito e retornar posição
grep("\\d", str, value = T) # \\ buscar por tudo que for ditigo e retornar conteúdo


# grepl()
?grepl
grepl("\\d+", str) # \\d+ buscar digito e palavra e retornar: TRUE|FALSE
grepl("\\D", str)  # \\D  bucar tudo não digito e retornar: TRUE|FALSE


========================================================================================================================

                          
                        # gsub() - Substituir padrão por outro valor ou Remover

?gsub
gsub("em", "***", str)
gsub("ex", "EX", str, ignore.case = T)


# sub()
sub("em", "EM", str)

========================================================================================================================


                        # regexpr () - mapear posicionamento
# regexpr()
frase <- "Isso é uma string."
regexpr(pattern = "u", frase) # posicionamento da letra u em "frase




# gregexpr()
gregexpr(pattern = "u", frase)


========================================================================================================================



str2 <- c("2678 é maior que 45 - @???!§$",
          "Vamos escrever 14 scripts R")

str2

# gsub()
gsub("\\d", "", str2) # encontrou digito, remove
gsub("\\D", "", str2) # encontrou não-digito, remove
gsub("\\s", "", str2) # encontrou espaço, remove
gsub("[iot]", "Q", str2) 
gsub("[[:punct:]]", "", str2)






