---
title: "R Notebook"
output: html_notebook
---

                                                   # Funções Especiais



- unlist() {base} # Achatando listas em vetor 
#muito aplicado em Deep Learning antes de treinar o modelo. O conjunto multidimensional é achatado em um objeto em uma dimensão

- do.call()
- strsplit()


========================================================================================================================


                                        # unlist() - Produz um vetor com os elementos da lista
?unlist
# a princípio, é possível criar uma lista com vários elementos diferentes, que podem ser vetores ou matrizes.
# e se quisermos fazer o contrário? como obter cada vetor, cada elemento de uma lista de forma separada?


lst1 <- list(6, "b", 15) # 3 elementos na lista
lst1 
class(lst1) #o. "list"

unlist(lst1) # Queremos transformar esta lista em um flatten
vec1 <- unlist(lst1) # Passar lista como parâmetro de unlist

class(vec1) #o. "character"
vec1        #o. "6", "b", "15" - como um dos elementos era caracter, todos foram transformados em caracter.


========================================================================================================================


                                                         # unlist()


lst2 <- list(v1 = 6,                 # valor único, escalar
             v2 = list(381, 2190),   # lista
             v3 = c(30, 217))        # vetor multidimensional
lst2



unlist(lst2) # aplicar unlist à "super lista" - o. objeto unidimensional COM TÍTULO derivado do posicionamento da dimensão anterior

mean(unlist(lst2)) # muito mais prático aplicar função aos elementos da lista quando em uma dimensão apenas
round(mean(unlist(lst2)))


========================================================================================================================


                                                        # do.call()

# Executa uma chamada de função em um objeto


# *** ATENÇÃO ***
# As funções da família apply aplicam UMA FUNÇÃO A CADA ELEMENTO de um objeto (substitui um loop)


# A função do.call aplica uma função ao objeto inteiro e não a cada elemento individualmente - Como se fosse uma ESTRUTURA ÚNICA
?do.call

data <- list() # Criando uma lista vazia
N <- 100       # Criando N com valor 100

for (n in 1:N) { 
  data[[n]] = data.frame(index = n, char = sample(letters, 1), z = rnorm(1)) # Preencher a lista
}

========================================================================================================================

head(data)

do.call(rbind, data) # Combinação por linha
class(do.call(rbind, data))

# lapply() x do.call()
y <- list(1:3, 4:6, 7:9)
y

lapply(y, sum) # soma cada elemento da lista o. 6  16  24
do.call(sum, y) # soma todos os elemtnos o. 46


# O resultado da função lapply() pode ser obtido de outras formas
# Pacote plyr

install.packages('plyr')
library(plyr)

y <- list(1:3, 4:6, 7:9)
y

ldply(y, sum) 


========================================================================================================================


                                                        # strsplit()



# Divide uma string ou vetor de caracteres

texto <- "Data Science Academy" #um único objeto 
strsplit(texto, " ")            #dividir objeto texto por espaço e formar um vetor de 3 palavras

texto <- "Data Science Academy" #um único objeto 
strsplit(texto, "")             #considera separação de todos os caracteres sem espaçamento de aspas - vetor de 18 caracteres


dates <- c("1998-05-23", "2008-12-30", "2009-11-29") # vetor de "datas" em string
temp  <- strsplit(dates, "-")                        # fazer split por caracter -
temp                                                 # o. 3 vetores, com 3 elementos (ano, mês, dia)
class(temp) #o. "list"





========================================================================================================================


                                    # Transforma a lista em matriz, fazendo antes um unlist()


matrix(unlist(temp), ncol = 3, byrow = TRUE)

Names <- c("Brin, Sergey", "Page, Larry",
           "Dorsey, Jack", "Glass, Noah",
            "Williams, Evan", "Stone, Biz")

temp <- strsplit(Names, ", ")
temp

========================================================================================================================


frase <- "Muitas vezes temos que repetir algo diversas vezes e essas diversas vezes parecem algo estranho"
palavras <- strsplit(frase, " ")[[1]] # Acessando primeiro elemento da lista de unlist
palavras
unique(tolower(palavras)) # converter os elementos do objeto palavras pra minúsculas
                          # tornar apenas palavras única


========================================================================================================================


                               # strplit() com dataframes - extremamente útil para extração de dados. Resultado final é uma LISTA


antes = data.frame(attr = c(1,30,4,6), tipo = c('pao_e_agua','pao_e_agua_2'))
antes
strsplit(as.character(antes$tipo),'_e_' #utilizando a coluna tipo do dataset antes, converter para caracter e depoist strsplit com padrão _e_
         


         ========================================================================================================================
                             
                              # str_split_fixed {stringr} - Resultado final é uma MATRIZ
         
library(stringr)
str_split_fixed(antes$tipo, "_e_", 2) # executa praticamente a mesma coisa, mas resultado final é uma MATRIZ

         
         

         
========================================================================================================================
         
         
# Usando do.call()
antes = data.frame(attr = c(1,30,4,6), tipo = c('pao_e_agua','pao_e_agua_2'))
antes
         
         
depois <- strsplit(as.character(antes$tipo),'_e_')
depois
         
do.call(rbind, depois) #união por linhas da dataset depois


========================================================================================================================
         
                                   # Pacotes Tidyverse
                   # Vantagens em performance e e de execução de comandos
         
# Usando dplyr e tidyr
install.packages("dplyr") 
install.packages("tidyr")
library(dplyr)
library(tidyr)

         
antes <- data.frame(
  attr = c(1, 30 ,4 ,6 ), 
  tipo = c('pao_e_agua','pao_e_agua_2')
)

         
       
antes %>% # antes é o dataframe, pipe é um caracter de concatenação 
  separate(tipo, c("pao", "agua"), "_e_") # função de separação 
 #separate(coluna, c(palavras a separar), "qual o critério)



