---
title: "R Notebook"
output: html_notebook
---

# Trabalhando com arquivos csv


# Usando o pacote readr 
install.packages("readr")
library(readr)

---------------------------------------------------------------------------------------------------------------------------------

# Abre o promt para escolher o arquivo
meu_arquivo <- read_csv(file.choose()) # Muito ÚTIL para importação de arquivos


# Importando arquivos
df1 <- read_table("temperaturas.txt", 
                  col_names = c("DAY","MONTH","YEAR","TEMP"))

head(df1)
View(df1)
str(df1)

read_lines("temperaturas.txt", skip = 0, n_max = -1L)
read_file("temperaturas.txt")

---------------------------------------------------------------------------------------------------------------------------------

# Exportando e Importando
write_csv(iris, "iris.csv")
dir()

# col_integer(): 
# col_double(): 
# col_logical(): 
# col_character(): 
# col_factor(): 
# col_skip(): 
# col_date() (alias = “D”), col_datetime() (alias = “T”), col_time() (“t”) 

df_iris <- read_csv("iris.csv", col_types = list(
  Sepal.Length = col_double(),
  Sepal.Width = col_double(),
  Petal.Length = col_double(),
  Petal.Width = col_double(),
  Species = col_factor(c("setosa", "versicolor", "virginica"))
))

dim(df_iris)
str(df_iris)

---------------------------------------------------------------------------------------------------------------------------------

# Manipulando arquivos csv
df_cad <- read_csv("cadastro.csv")
View(df_cad)
class(df_cad)


install.packages("dplyr")
library(readr) #  importa arquivos
library(dplyr) # manipula arquivos

options(warn=-1)

---------------------------------------------------------------------------------------------------------------------------------

df_cad <- tbl_df(df_cad) 
# Converter objeto em dataframe tibble

head(df_cad)
View(df_cad)

write.csv(df_cad, "df_cad_bkp.csv")
# Gravar objeto|dataframe, chamar a função write.csv() ou write_csv()

---------------------------------------------------------------------------------------------------------------------------------

# Importando vários arquivos simultaneamente - Muito Útil

list.files() # Listar todos os arquivos do presente diretório

lista_arquivos <- list.files('C:/FCD/BigDataRAzure/Cap05/arquivos', full.names = TRUE)
class(lista_arquivos)
lista_arquivos

lista_arquivos2 <- lapply(lista_arquivos, read_csv)
# lapply aplicará a função em loop na lista de arquivos.
# Método para carregar múltiplos arquivos

class(lista_arquivos2) # Objeto é uma lista de arquivos
View(lista_arquivos2) 

---------------------------------------------------------------------------------------------------------------------------------

# Parsing  - parse_date permite ajustar o formato de data
# Problema recorrente na importação de arquivos
parse_date("01/02/15", "%m/%d/%y")
parse_date("01/02/15", "%d/%m/%y")
parse_date("01/02/28", "%y/%m/%d")

# Esta função especifica com qual idioma trabalharemos - Muito Útil
# Retornará os parâmetros e formatos para o idioma 
locale("en")
locale("fr")
locale("pt")



                   
